# Generated by Django 2.2.5 on 2019-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesimages', '0002_memesimages_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesimages',
            name='images',
            field=models.TextField(),
        ),
    ]
