# Generated by Django 2.2.4 on 2019-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesimages',
            name='category',
            field=models.CharField(default='t', max_length=2),
            preserve_default=False,
        ),
    ]
