# Generated by Django 2.2.5 on 2019-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('images', models.ImageField(upload_to='pics')),
                ('category', models.CharField(max_length=2)),
                ('page', models.TextField()),
                ('flag', models.BooleanField(primary_key=True, serialize=False)),
            ],
        ),
    ]
