# Generated by Django 2.2.5 on 2019-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='page',
            field=models.TextField(max_length=3),
        ),
    ]
