# Generated by Django 2.2.5 on 2019-12-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0002_auto_20191222_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
