# Generated by Django 2.2.5 on 2019-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0003_auto_20191222_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='page',
            field=models.TextField(max_length=2),
        ),
    ]
