# Generated by Django 2.2.4 on 2019-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='image',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='emp_id',
            field=models.IntegerField(verbose_name='pics'),
        ),
    ]
