# Generated by Django 2.2.4 on 2019-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20190813_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
